### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Kuangxiyang** [helenypzhang/Subspace-Multimodal-Learning#1]
Hello, do you have relevant data files?

**Comment by helenypzhang** [comment]
https://portal.gdc.cancer.gov/projects/TCGA-LGG
https://portal.gdc.cancer.gov/projects/TCGA-GBM
https://www.cancerimagingarchive.net/collection/ivygap/

**Comment by Kuangxiyang** [comment]
Thank you for your reply. Good luck with your work！




ぐ柒拾丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "helenypzhang/Subspace-Multimodal-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月12日(星期五) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [helenypzhang/Subspace-Multimodal-Learning] data (Issue #1)





 
https://portal.gdc.cancer.gov/projects/TCGA-LGG
 https://portal.gdc.cancer.gov/projects/TCGA-GBM
 https://www.cancerimagingarchive.net/collection/ivygap/
